### PR TITLE
Adding missing zookeper package

### PR DESCRIPTION
**Pull request by ynachiket**
Adding the missing dependency to package.json

### CODE REVIEW

**Comment by Raynos** [comment]
Zookeeper is a dev dependency

**Comment by ynachiket** [comment]
@Raynos fixed in  318a2a5

**Comment by Raynos** [comment]
This change is already being added in https://github.com/uber/nodesol-write/pull/5/files so we'll merge that one instead to avoid merge conflicts.

**Comment by ynachiket** [comment]
@Raynos thanks. Will close this out.

**Pull request closed without merging**
